services:
  - type: web
    name: url-shortener
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=8000
    envVars:
      - key: BASE_URL
        fromService:
          name: url-shortener
          type: web
          property: url